[theme]
# Primary accent color for interactive elements.
primaryColor = "#233928"

# Background color for the main content area.
backgroundColor = "#27332b"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#2c6437"

# Color used for almost all text.
textColor = "#eef0f3"

# Font family for all text in the app, except code blocks. One of "sans serif", "serif", or "monospace".
# Default: "sans serif"
font = "sans serif"
